- name: check if we're building on a supported os
  assert:
    fail_msg: "{{ role_name }} only supports ubuntu versions 16, 18, 20 and centos versions 6, 7!"
    success_msg: "{{ role_name }} supports {{ ansible_distribution }} version {{ ansible_distribution_version }}"
    quiet: "{{ not ansible_check_mode }}"
    that:
      ( ansible_distribution == "Ubuntu" and ansible_distribution_version|int in [16, 18, 20] )
      or ( ansible_distribution == "CentOS" and ansible_distribution_major_version|int in [7, 8] )
      or ( ansible_distribution|lower == "redhat" and ansible_distribution_major_version|int in [8] )



- name: add the rabbit repo key'
  rpm_key:
    state: present
    key: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc


- name: add the erlang repo
  yum_repository:
    name: erlang
    description: Erlang repo
    baseurl: https://packagecloud.io/rabbitmq/erlang/gpgkey

- name: add the rabbit mq repo
  yum_repository:
    name: rabbitmq
    description: Rabbitmq repo
    baseurl: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey


- name: "Install rabbitmq on target servers "
  ansible.builtin.package:
    name:  '{{ item  }}'
    state: present
  with_items:
    - "rabbitmq-server"