- name: 'clone git repo ({{ outer_item.key }} - {{ outer_item.value.ostackversion }})'
  ansible.builtin.git:
    repo: 'https://github.com/openstack/{{ outer_item.key }}.git'
    dest: '/tmp/builder/checkout/{{ outer_item.key }}/{{ outer_item.value.ostackversion }}'
    version: '{{ outer_item.value.ostackversion }}'

- name: add the rabbit repo key'
  rpm_key:
    state: present
    key: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc


- name: add the erlang repo
    name: erlang
    description: Erlang repo
    baseurl: https://packagecloud.io/rabbitmq/erlang/gpgkey

- name: add the rabbit mq repo
  yum_repository:
    name: rabbitmq
    description: Rabbitmq repo
    baseurl: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey

