---
- include: redhat.yml
  when: ( ansible_distribution|lower == "redhat" and ansible_distribution_major_version|int in [8] )
  
#- name: checking to see if already clustered
#  stat: path=/etc/mysqld/clustered
#  register: clustered

#- include: rabbitmq_clustering.yml
#  when: enable_mysqld_clustering and (clustered.stat.exists != True)

#- include: mysqld_ha_config.yml
#  when: config_mysqld_ha and enable_mysqld_clustering

