---
- hosts: all
  gather_facts: yes
  tasks:
   - name: Dump all variables
     action: template src=dumpall.j2 dest=/tmp/ansible_dump.all

- hosts: builders
  gather_facts: yes
  vars:
    components: 
     [ 
        { name: "keystone", version: "stable/train"}, 
        { name: "horizon", version: "stable/train"},
        { name: "glance", version: "stable/train"},
        { name: "swift", version: "stable/train"},
        { name: "keystone", version: "stable/stein"},
        { name: "horizon", version: "stable/stein"},
        { name: "glance", version: "stable/stein"},
        { name: "swift", version: "stable/stein"}
     ]
  roles:
    - role: ansible_role_build_ostack_components
  loop: components

#- hosts: api
#  gather_facts: yes
#  roles:
#    - role: ansible-role-rabbitmq
#    - role: ansible-role-mariadb





