---
- hosts: all
  gather_facts: yes
  tasks:
   - name: Dump all variables
     action: template src=dumpall.j2 dest=/tmp/ansible_dump.all

- hosts: api
  gather_facts: yes
  roles:
#   - role: ansible-role-rabbitmq
   - role: ansible-role-mysqld





