---
- hosts: builders
  gather_facts: yes
  tasks:
    - name: Loop over components
      include_role:
        name: ansible_role_build_ostack_components
      vars:
         component: " {{ item  }}"
      with_items:
           - { name: "keystone", version: "stable/train"} 




