- name: build_virtual_environments | check if we're building on a supported os
  assert:
    fail_msg: "{{ role_name }} only supports ubuntu versions 16, 18, 20 and centos versions 6, 7!"
    success_msg: "{{ role_name }} supports {{ ansible_distribution }} version {{ ansible_distribution_version }}"
    quiet: "{{ not ansible_check_mode }}"
    that:
      ( ansible_distribution == "Ubuntu" and ansible_distribution_version|int in [16, 18, 20] )
      or ( ansible_distribution == "CentOS" and ansible_distribution_major_version|int in [7, 8] )
      or ( ansible_distribution|lower == "redhat" and ansible_distribution_major_version|int in [8] )

- name: build_virtual_environments | ansible create directory example
  file:
    path: /var/lib/venv/openstack/venv/rpmvenv/
    state: directory
    recurse: yes

- name: build_virtual_environments | Create a file for ldconfig to load to ensure access to /usr/local/lib
  ansible.builtin.copy:
    src: lib.local.usr.conf
    dest: /etc/ld.so.conf.d/local.conf
    owner: root
    group: root
    mode: '0644'

- name: build_virtual_environments | run ldconfig in a shell
  ansible.builtin.shell: ldconfig
  become: True

- name: build_virtual_environments | Install tools on build servers
  ansible.builtin.package:
    name:  '{{ item  }}'
    state: present
  with_items:
    - "git"
    - "python3-pip"
    - "python3-devel"
    - "make" 
    - "autoconf" 
    - "automake" 
    - "libtool" 
    - "gcc"
    - "zlib-devel"
    - "rpm-build"
      #    - "liberasurecode-devel"


##########################################################
# Common prereqs for running openstack
#
# liberasurecode
# --------------
# https://github.com/openstack/liberasurecode.git to be complied
#
#
###########################################################

- name: build_virtual_environments | clone liberasurecode git repo
  ansible.builtin.git:
    repo: https://github.com/openstack/liberasurecode.git
    dest: /tmp/builder/checkout/liberasurecode

- name: build_virtual_environments | run autogen
  ansible.builtin.command: ./autogen.sh
  args:
    chdir: /tmp/builder/checkout/liberasurecode
  become: True

- name: build_virtual_environments | run configure
  ansible.builtin.command: ./configure
  args:
    chdir: /tmp/builder/checkout/liberasurecode
  become: True

- name: build_virtual_environments | run make
  ansible.builtin.command: make
  args:
    chdir: /tmp/builder/checkout/liberasurecode
  become: True

- name: build_virtual_environments | run make test
  ansible.builtin.command: make test
  args:
    chdir: /tmp/builder/checkout/liberasurecode
  become: True

- name: build_virtual_environments | run make install
  ansible.builtin.command: make install
  args:
    chdir: /tmp/builder/checkout/liberasurecode
  become: True

- name: build_virtual_environments | run pip update
  ansible.builtin.command: pip3 install --upgrade pip
  become: True

- name: build_virtual_environments | run pip update
  ansible.builtin.command: pip3 install --upgrade virtualenv
  become: True

- name: build_virtual_environments | run pip install rpmvenv
  ansible.builtin.command: pip3 install rpmvenv
  become: True

- name: 'clone git repo ({{ outer_item.key }} - {{ outer_item.value.ostackversion }})'
  ansible.builtin.git:
    repo: 'https://github.com/openstack/{{ outer_item.key }}.git'
    dest: '/tmp/builder/checkout/{{ outer_item.key }}/{{ outer_item.value.ostackversion }}'
    version: '{{ outer_item.value.ostackversion }}'

- name: "Cleanup - Recursively remove directory ({{ outer_item.key }} - {{ outer_item.value.ostackversion }})"
  ansible.builtin.file:
    path: '/tmp/builder/virtualenvironments/{{ outer_item.key }}/{{ outer_item.value.ostackversion }}/venv'
    state: absent

- name: "Build a virtual environment face 1 init virtual env  ({{ outer_item.key }} - {{ outer_item.value.ostackversion }})"
  pip:
    name: pip
    virtualenv: '/tmp/builder/virtualenvironments/{{ outer_item.key }}/{{ outer_item.value.ostackversion }}/venv'
    state: latest

- name: "Build a virtual environment face 2 : update pip ({{ outer_item.key }} - {{ outer_item.value.ostackversion }})"
  pip:
    name: ['setuptools', 'setuptools-rust', 'wheel']
    virtualenv: '/tmp/builder/virtualenvironments/{{ outer_item.key }}/{{ outer_item.value.ostackversion }}/venv'
    state: latest

- name: "Build a virtual environment for ({{ outer_item.key }} - {{ outer_item.value.ostackversion }})"
  pip:
    requirements: '/tmp/builder/checkout/{{ outer_item.key }}/{{ outer_item.value.ostackversion }}/requirements.txt'
    virtualenv: '/tmp/builder/virtualenvironments/{{ outer_item.key }}/{{ outer_item.value.ostackversion }}/venv'
    state: latest

- name: Template a file to /etc/file.conf
  ansible.builtin.template:
    src: templates/rpmvenv.json.j2
    dest: '/var/lib/venv/openstack/venv/rpmvenv/{{ outer_item.key }}.{{ outer_item.value.ostackversion.split("/")[1] }}.rmpvenv.json'
    force: yes